---

- name: run "apt-get" update
  apt:
    update_cache: yes

- name: run "apt-get" Docker Development Tools Net Tools Htop Vim Tmux
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker.io
    - build-essential
    - net-tools
    - htop
    - vim
    - tmux
    - unzip

- name: wget Terraform and run checksum 
  get_url: 
    url: https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip
    dest: /vagrant/terraform_0.11.3_linux_amd64.zip
    checksum: sha256:6b8a7b83954597d36bbed23913dd51bc253906c612a070a21db373eab71b277b

- name: un-archive Terraform
  unarchive:
    src: /vagrant/terraform_0.11.3_linux_amd64.zip
    dest: /vagrant

- name: Move Terraform binary to /usr/local/bin
  command: mv /vagrant/terraform /usr/local/bin